/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AppRouteRouteImport } from "./routes/app/route"
import { Route as authSignInRouteImport } from "./routes/(auth)/sign-in"
import { Route as authSignUpRouteImport } from "./routes/(auth)/sign-up"
import { Route as AppUserIndexRouteImport } from "./routes/app/user/index"

const AppRouteRoute = AppRouteRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: "/(auth)/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: "/(auth)/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: "/user/",
  path: "/user/",
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/app": typeof AppRouteRouteWithChildren
  "/sign-in": typeof authSignInRoute
  "/sign-up": typeof authSignUpRoute
  "/app/user/": typeof AppUserIndexRoute
}
export interface FileRoutesByTo {
  "/app": typeof AppRouteRouteWithChildren
  "/sign-in": typeof authSignInRoute
  "/sign-up": typeof authSignUpRoute
  "/app/user": typeof AppUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/app": typeof AppRouteRouteWithChildren
  "/(auth)/sign-in": typeof authSignInRoute
  "/(auth)/sign-up": typeof authSignUpRoute
  "/app/user/": typeof AppUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/app" | "/sign-in" | "/sign-up" | "/app/user/"
  fileRoutesByTo: FileRoutesByTo
  to: "/app" | "/sign-in" | "/sign-up" | "/app/user"
  id: "__root__" | "/app" | "/(auth)/sign-in" | "/(auth)/sign-up" | "/app/user/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/app": {
      id: "/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)/sign-in": {
      id: "/(auth)/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)/sign-up": {
      id: "/(auth)/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/user/": {
      id: "/app/user/"
      path: "/user"
      fullPath: "/app/user/"
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppUserIndexRoute: typeof AppUserIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppUserIndexRoute: AppUserIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
