/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as authSignInRouteImport } from "./routes/(auth)/sign-in"
import { Route as authSignUpRouteImport } from "./routes/(auth)/sign-up"
import { Route as AppIndexRouteImport } from "./routes/app/index"
import { Route as AppUserRouteImport } from "./routes/app/user"

const authSignInRoute = authSignInRouteImport.update({
  id: "/(auth)/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: "/(auth)/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/app/",
  path: "/app/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: "/app/user",
  path: "/app/user",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/sign-in": typeof authSignInRoute
  "/sign-up": typeof authSignUpRoute
  "/app/user": typeof AppUserRoute
  "/app/": typeof AppIndexRoute
}
export interface FileRoutesByTo {
  "/sign-in": typeof authSignInRoute
  "/sign-up": typeof authSignUpRoute
  "/app/user": typeof AppUserRoute
  "/app": typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/(auth)/sign-in": typeof authSignInRoute
  "/(auth)/sign-up": typeof authSignUpRoute
  "/app/user": typeof AppUserRoute
  "/app/": typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/sign-in" | "/sign-up" | "/app/user" | "/app/"
  fileRoutesByTo: FileRoutesByTo
  to: "/sign-in" | "/sign-up" | "/app/user" | "/app"
  id: "__root__" | "/(auth)/sign-in" | "/(auth)/sign-up" | "/app/user" | "/app/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  AppUserRoute: typeof AppUserRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(auth)/sign-in": {
      id: "/(auth)/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)/sign-up": {
      id: "/(auth)/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/": {
      id: "/app/"
      path: "/app"
      fullPath: "/app/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/user": {
      id: "/app/user"
      path: "/app/user"
      fullPath: "/app/user"
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  AppUserRoute: AppUserRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
